name: CI/CD

on: 
  push:
    branches-ignore: 
      - gh-pages

jobs:
  build-latex:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@master
      with:
        root_file: presentation/slides.tex
        args: -xelatex -file-line-error -interaction=nonstopmode
    - name: list
      run: ls presentation
    - uses: actions/upload-artifact@v1
      with:
        name: slides.pdf
        path: presentation/slides.pdf
    - name: GitHub Pages Deploy 
      uses: maxheld83/ghpages@v0.2.1
    
