name: CI/CD

on: 
  push:
    branches-ignore: 
      - gh-pages

jobs:
  build-latex:
    name: Build latex presentation files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: "maxheld83/pandoc@v0.1.0"
      name: convert Workshop.md to latex
      with:
          args: "-so Workshop.tex -t latex Workshop.md"
    - name: Compile Workshop.tex
      uses: xu-cheng/latex-action@master
      with:
          root_file: Workshop.tex
    - name: Compile slides.tex
      uses: xu-cheng/latex-action@master
      with:
        root_file: slides.tex
        args: -xelatex -file-line-error -interaction=nonstopmode
        working_directory: presentation
    - name: Compile slides_with_notes.tex
      uses: xu-cheng/latex-action@master
      with:
        root_file: slides_with_notes.tex
        args: -xelatex -file-line-error -interaction=nonstopmode
        working_directory: presentation
    - name: move output
      run: mkdir slides;cp presentation/slides.pdf slides/;cp presentation/slides_with_notes.pdf slides/;cp Workshop.pdf slides/
    - uses: actions/upload-artifact@v1
      with:
        name: slides
        path: slides
  build-survey:
    name: Build survey docker container
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: docker login
      run: docker login docker.pkg.github.com --username RobinMarchart --password-stdin <<< "${{ secrets.GITHUB_TOKEN }}" && docker login --username robinmarchart --password-stdin <<< "${{ secrets.DOCKER_HUB }}"
    - name: build survey container
      run: docker build survey -f ./survey/Dockerfile --tag robinmarchart/workshop:latest && docker tag robinmarchart/workshop:latest docker.pkg.github.com/robinmarchart/workshop-wissenschaftstag/survey:latest
    - name: rudimentary container test - run 60 seconds
      run: if timeout 60 docker run --rm robinmarchart/workshop:latest || [ $? = 143 ];then exit 0;else exit 1;fi
    - name: publish survey container
      run: docker push robinmarchart/workshop:latest && docker push docker.pkg.github.com/robinmarchart/workshop-wissenschaftstag/survey:latest
    - name: docker logout
      run: docker logout
      if: always()
  deploy-pages:
    name: Publish Gh-Pages
    runs-on: ubuntu-latest
    needs: [build-latex]
    steps:
      - uses: actions/checkout@v1
      - name: GH Pages deploy
        uses: Cecilapp/GitHub-Pages-deploy@2.0.0
        env:
          EMAIL: robin.marchart@hotmail.com               
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BUILD_DIR: site/
      
    

    

      
